[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.api"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"
startCommand = "uvicorn app.api.main:app --host 0.0.0.0 --port 8000"